version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '49153:5432'
    volumes:
      - data:/data/db
    environment:
      POSTGRES_USER: u_appdata
      POSTGRES_PASSWORD: pw_appdata
      TZ: 'GMT+2'
      PGTZ: 'GMT+2'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

#  backend:
#    build: ./backend
#    ports:
#      - '8080:8080'
#    volumes:
#      - logs:/app/logs
#      - ./backend:/app
#    env_file:
#      - ./env/backend.env
#    depends_on:
#      - postgres

volumes:
  elasticsearch-data-volume:
    driver: local
  data: